=== edie-yao-0207/datahubcursorllm-edie/dataplatform/_json_schemas/s3table_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "S3 table definition schema",
  "type": "object",
  "column": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "type": {
        "type": ["string", "object"],
        "anyOf": [
          { "pattern": "^decimal\\([0-9]+,[0-9]+\\)$" },
          {
            "enum": [
              "string",
              "binary",
              "boolean",
              "date",
              "timestamp",
              "double",
              "float",
              "byte",
              "integer",
              "long",
              "bigint",
              "short",
              "array",
              "map",
              "struct"
            ]
          }
        ]
      },
      "fields": {
        "type": "array"
      },
      "nullable": {
        "type": "boolean"
      },
      "description": {
        "type": "string"
      }
    },
    "if": {
      "properties": { "type": { "const": "struct" } }
    },
    "then": {
      "required": ["name", "type", "fields"]
    },
    "else": {
      "required": ["name", "type"]
    }
  },
  "properties": {
    "table": {
      "type": "string",
      "description": "Name of table"
    },
    "owner": {
      "type": "string",
      "description": "Team that is going to own the table"
    },
    "description": {
      "type": "string",
      "description": "Description of table"
    },
    "database": {
      "type": "string",
      "description": "Name of database table will be under"
    },
    "region_to_location": {
      "type": "object",
      "description": "map of region to S3 location of data that table is based on"
    },
    "datatype": {
      "type": "string",
      "description": "File type of data, currently only csv supported",
      "enum": ["csv", "json"]
    },
    "schema": {
      "description": "The output schema",
      "type": "array",
      "items": { "$ref": "#/column" }
    },
    "csv": {
      "type": "object",
      "description": "CSV format specifications",
      "additionalProperties": false,
      "properties": {
        "separator": {
          "type": "string",
          "description": "A separator (one or more characters) for each field and value (default: ,)"
        },
        "quote": {
          "type": "string",
          "description": "A single character used for escaping quoted values where the separator can be part of the value (default: \")"
        },
        "escape": {
          "type": "string",
          "description": "A single character used for escaping quotes inside an already quoted value (default: \\)"
        },
        "header": {
          "type": "boolean",
          "description": "First line contains names of columns (default: false)"
        },
        "multiline": {
          "type": "boolean",
          "description": "Parse multiline records (default: false)"
        }
      }
    },
    "json": {
      "type": "object",
      "description": "JSON format specifications",
      "additionalProperties": false,
      "properties": {
        "inferSchema": {
          "type": "boolean",
          "description": "Infer schema (default: false)"
        }
      }
    },
    "partitions": {
      "type": "array",
      "description": "List of columns to partition on",
      "items": { "$ref": "#/column" }
    }
  },
  "required": ["table", "owner", "description", "database", "datatype", "schema"],
  "additionalProperties": false
}

=== edie-yao-0207/datahubcursorllm-edie/dataplatform/tables/s3data/definitions/j1939_txid_to_source.json
{
  "table": "j1939_txid_to_source",
  "owner": "FirmwareVdp",
  "description": "This table maps source identifiers defined in J1939-DA to english. THIS TABLE IS AUTOGENERATED. For updates, modify go/infra/vdp.",
  "database": "definitions",
  "datatype": "csv",
  "schema": [
    {
      "name": "id",
      "type": "bigint"
    },
    {
      "name": "name",
      "type": "string"
    }
  ]
}

=== edie-yao-0207/datahubcursorllm-edie/dataplatform/tables/s3data/definitions/can_id_type.json
{
  "table": "can_id_type",
  "owner": "FirmwareVdp",
  "description": "CanConfig_CanIdType enum mapping table. THIS TABLE IS AUTOGENERATED. For updates, modify go/infra/vdp.",
  "database": "definitions",
  "datatype": "csv",
  "schema": [
    {
      "name": "id",
      "type": "bigint",
      "description": "The id of the can id type."
    },
    {
      "name": "name",
      "type": "string",
      "description": "The name of the can id type."
    }
  ]
}

=== edie-yao-0207/datahubcursorllm-edie/dataplatform/tables/s3data/fuel_maintenance/historical_ifta_report.json
{
  "table": "historical_ifta_report",
  "owner": "IftaCore",
  "description": "Historical IFTA data from reports v1. This data is needed to allow customers to view historical data after the switch over to reports v2 using data pipelines. This table is joined with the IFTA report in the combined_distance table.",
  "database": "fuel_maintenance",
  "region_to_location": {
    "us-west-2": "s3://samsara-databricks-playground/historical-ifta-daily/",
    "eu-west-1": "s3://samsara-eu-databricks-playground/historical-ifta-daily/",
    "ca-central-1": "s3://samsara-ca-databricks-playground/historical-ifta-daily/"
  },
  "datatype": "csv",
  "schema": [
    { "name": "org_id", "type": "bigint", "description": "$org_id_default_description" },
    { "name": "device_id", "type": "bigint", "description": "The device id of this hour of data." },
    {
      "name": "driver_id",
      "type": "bigint",
      "description": "The id of the driver assigned to this vehicle during this hour of data."
    },
    { "name": "jurisdiction", "type": "string", "description": "The jurisdiction this hour of driving took place in." },
    { "name": "end_ms", "type": "bigint", "description": "The end time in milliseconds of this hour of data." },
    {
      "name": "duration_ms",
      "type": "bigint",
      "description": "The duration in milliseconds of this hour of data. This will always be 3,600,000 ms (1 hour)."
    },
    {
      "name": "gps_distance_m",
      "type": "bigint",
      "description": "The distance traveled in meters as recorded by GPS during this hour. This is calculated using our trips-based algorithm."
    },
    {
      "name": "odo_distance_m",
      "type": "bigint",
      "description": "The distance traveled in meters as recorded by odometer during this hour. This is calculated using our trips-based algorithm."
    },
    {
      "name": "toll_distance_m",
      "type": "bigint",
      "description": "The distance traveled in meters on toll roads during this hour. This is calculated using our trips-based algorithm."
    },
    {
      "name": "time_ms",
      "type": "bigint",
      "description": "The duration the engine was running, in milliseconds, during this hour. This is calculated using our trips-based algorithm."
    },
    {
      "name": "tripless_gps_distance_m",
      "type": "bigint",
      "description": "The distance traveled in meters as recorded by GPS during this hour. This is calculated using our tripless algorithm, which does not depend on trips to calculate distance."
    },
    {
      "name": "tripless_odo_distance_m",
      "type": "bigint",
      "description": "The distance traveled in meters as recorded by odometer during this hour. This is calculated using our tripless algorithm, which does not depend on trips to calculate distance."
    },
    {
      "name": "tripless_toll_distance_m",
      "type": "bigint",
      "description": "The distance traveled in meters on troll roads during this hour. This is calculated using our tripless algorithm, which does not depend on trips to calculate distance."
    },
    {
      "name": "tripless_engine_on_ms",
      "type": "bigint",
      "description": "The duration the engine was running, in milliseconds, during this hour. This is calculated using our tripless algorithm, which does not depend on trips to calculate distance."
    },
    {
      "name": "use_odometer",
      "type": "boolean",
      "description": "A boolean value that denotes whether this org was using odometer values to calculate IFTA distances during this time."
    },
    {
      "name": "use_tripless",
      "type": "boolean",
      "description": "A boolean value that denotes whether this org was using the tripless algorithm to calculate IFTA distances during this time."
    }
  ],
  "partitions": [{ "name": "date", "type": "timestamp", "description": "The date of this hour of data." }]
}

=== edie-yao-0207/datahubcursorllm-edie/dataplatform/tables/s3data/definitions/obd_value_lock_cleared_reason.json
{
  "table": "obd_value_lock_cleared_reason",
  "owner": "FirmwareVdp",
  "description": "Map OBD VALUE locking cleared reasons using ObdLock logic. THIS TABLE IS AUTOGENERATED. For updates, modify go/infra/vdp.",
  "database": "definitions",
  "datatype": "csv",
  "schema": [
    {
      "name": "id",
      "type": "bigint",
      "description": "The id of the OBD value lock cleared reason."
    },
    {
      "name": "name",
      "type": "string",
      "description": "The name of the OBD value lock cleared reason."
    }
  ]
}

=== edie-yao-0207/datahubcursorllm-edie/dataplatform/tables/s3data/definitions/telematics_cet_vin_char.json
{
  "table": "telematics_cet_vin_char",
  "owner": "FirmwareVdp",
  "description": "Table 'vinChar' generated from 'Cable Recommendation CST Set (New Format).xlsx'.",
  "database": "definitions",
  "datatype": "csv",
  "schema": [
    {
      "name": "id",
      "type": "string"
    },
    {
      "name": "regions",
      "type": "string"
    },
    {
      "name": "make",
      "type": "string"
    },
    {
      "name": "model",
      "type": "string"
    },
    {
      "name": "year_start",
      "type": "bigint"
    },
    {
      "name": "year_end",
      "type": "bigint"
    },
    {
      "name": "engine_model",
      "type": "string"
    },
    {
      "name": "powertrain",
      "type": "string"
    },
    {
      "name": "fuel_group",
      "type": "string"
    },
    {
      "name": "priority",
      "type": "bigint"
    },
    {
      "name": "vin_pattern_start_position_values_1_17",
      "type": "bigint"
    },
    {
      "name": "vin_pattern_length",
      "type": "bigint"
    },
    {
      "name": "vin_patterns",
      "type": "string"
    },
    {
      "name": "exclude_models",
      "type": "string"
    },
    {
      "name": "count_row",
      "type": "bigint"
    },
    {
      "name": "return_code",
      "type": "string"
    },
    {
      "name": "cable",
      "type": "string"
    },
    {
      "name": "tacho_no",
      "type": "string"
    },
    {
      "name": "tacho_yes",
      "type": "string"
    },
    {
      "name": "vg34",
      "type": "boolean"
    },
    {
      "name": "vg54_nah",
      "type": "boolean"
    },
    {
      "name": "vg54_na_eu",
      "type": "boolean"
    },
    {
      "name": "vg55",
      "type": "boolean"
    },
    {
      "name": "ae_notes",
      "type": "string"
    }
  ]
}

=== edie-yao-0207/datahubcursorllm-edie/dataplatform/tables/s3data/definitions/state_params.json
{
  "table": "state_params",
  "owner": "FirmwareVdp",
  "description": "This table contains a mapping of ObjectStats to their ObjectStatState reporting configurations. This denotes how frequently we expect to receive and ObjectStat. Note that these are only default settings",
  "database": "definitions",
  "datatype": "csv",
  "schema": [
    {
      "name": "stat_type",
      "type": "string"
    },
    {
      "name": "int_threshold",
      "type": "bigint"
    },
    {
      "name": "double_threshold",
      "type": "double"
    },
    {
      "name": "min_period_ms",
      "type": "bigint"
    },
    {
      "name": "max_period_ms",
      "type": "bigint"
    }
  ]
}

=== edie-yao-0207/datahubcursorllm-edie/dataplatform/tables/s3data/definitions/j1708_autodetect_bus.json
{
  "table": "j1708_autodetect_bus",
  "owner": "FirmwareVdp",
  "description": "J1708CanAutodetectedBus enum mapping table. Reported using osDJ1708AutodetectResults. THIS TABLE IS AUTOGENERATED. For updates, modify go/infra/vdp.",
  "database": "definitions",
  "datatype": "csv",
  "schema": [
    {
      "name": "id",
      "type": "bigint",
      "description": "The id of the J1708 autodetect bus."
    },
    {
      "name": "name",
      "type": "string",
      "description": "The name of the J1708 autodetect bus."
    }
  ]
}

=== edie-yao-0207/datahubcursorllm-edie/dataplatform/tables/s3data/definitions/properties_fuel_fuelgroup.json
{
  "table": "properties_fuel_fuelgroup",
  "owner": "FirmwareVdp",
  "description": "The enum representing the Fuel Group for Fuel Properties. THIS TABLE IS AUTOGENERATED. For updates, modify go/infra/vdp.",
  "database": "definitions",
  "datatype": "csv",
  "schema": [
    {
      "name": "id",
      "type": "bigint",
      "description": "The id of the fuel group."
    },
    {
      "name": "name",
      "type": "string",
      "description": "The name of the fuel group."
    }
  ]
}
