=== edie-yao-0207/datahubcursorllm-edie/dataplatform/_json_schemas/s3view_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "S3 view definition schema",
  "column": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "type": {
        "type": "string"
      },
      "fields": {
        "type": "array",
        "items": { "$ref": "#/column" }
      },
      "description": {
        "type": "string"
      },
      "nullable": {
        "type": "boolean"
      }
    },
    "required": ["name", "type"],
    "additionalProperties": false
  },
  "type": "object",
  "properties": {
    "view": {
      "type": "string",
      "description": "Name of view"
    },
    "owner": {
      "type": "string",
      "description": "Team that is going to own the table"
    },
    "description": {
      "type": "string",
      "description": "Description of table"
    },
    "dependencies": {
      "description": "The other nodes that this node depends on",
      "type": "array",
      "items": {
        "oneOf": [{ "$ref": "#/definitions/table_dependency" }]
      }
    },
    "database": {
      "type": "string",
      "description": "Name of database table will be under"
    },
    "use_regional_values": {
      "type": "boolean",
      "description": "If true, the view's SQL may contain region specific template variables"
    },
    "schema": {
      "type": "array",
      "description": "Array of column objects containing name, type, and other columns",
      "items": {
        "$ref": "#/column"
      }
    },
    "regions": {
      "type": "array",
      "description": "Define the view in select AWS regions. Deploy to all regions by default if not specified.",
      "items": {
        "type": "string",
        "enum": ["us-west-2", "eu-west-1", "ca-central-1"],
        "minItems": 1
      }
    }
  },
  "required": ["owner", "description", "database", "schema"],
  "additionalProperties": false,

  "definitions": {
    "table_dependency": {
      "name": "table dependency",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "type": "object",
      "properties": {
        "dbname": {
          "type": "string"
        },
        "language": {
          "type": "string",
          "enum": ["python", "sql"]
        },
        "schema_path": {
          "type": "string"
        },
        "tablename": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": ["table"]
        },
        "external": {
          "type": "boolean"
        }
      },
      "required": ["dbname", "tablename", "type"],
      "additionalProperties": false
    }
  }
}

=== edie-yao-0207/datahubcursorllm-edie/dataplatform/tables/sqlview/mobile_metrics/mobile_media_queued_background_uploads.json
{
  "view": "mobile_media_queued_background_uploads",
  "owner": "Mobile",
  "description": "metrics for queued media uploads with background upload enabled",
  "database": "mobile_metrics",
  "schema": [
    {
      "name": "date",
      "type": "date"
    },
    {
      "name": "total_uploads",
      "type": "long"
    },
    {
      "name": "average_retries",
      "type": "double"
    },
    {
      "name": "duration_p95_ms",
      "type": "integer"
    },
    {
      "name": "duration_p99_ms",
      "type": "integer"
    },
    {
      "name": "duration_trimmed_mean_95",
      "type": "double"
    },
    {
      "name": "success_rate_overall",
      "type": "double"
    }
  ],
  "dependencies": [
    {
      "external": true,
      "dbname": "datastreams",
      "tablename": "mobile_logs",
      "type": "table"
    }
  ]
}

=== edie-yao-0207/datahubcursorllm-edie/dataplatform/tables/sqlview/product_analytics/map_org_sam_number_latest.json
{
  "view": "map_org_sam_number_latest",
  "owner": "DataEngineering",
  "description": "This view contains the latest org_id to sam_number mapping sourced from datamodel_core.dim_organizations. The latest sam_number corresponding to an org_id should be referenced at all times to account for sam_number changes.",
  "database": "product_analytics",
  "regions": ["us-west-2", "eu-west-1", "ca-central-1"],
  "schema": [
    { "name": "org_id", "type": "long", "description": "The Samsara cloud dashboard ID that the data belongs to" },
    {
      "name": "sam_number",
      "type": "string",
      "description": "Samnumber is a unique id that ties customer accounts together in Netsuite, Salesforce, and Samsara cloud dashboard."
    }
  ],
  "dependencies": [
    {
      "external": true,
      "dbname": "datamodel_core",
      "tablename": "dim_organizations",
      "type": "table"
    }
  ]
}
