=== edie-yao-0207/datahubcursorllm-edie/dataplatform/_json_schemas/s3view_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "S3 view definition schema",
  "column": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "type": {
        "type": "string"
      },
      "fields": {
        "type": "array",
        "items": { "$ref": "#/column" }
      },
      "description": {
        "type": "string"
      },
      "nullable": {
        "type": "boolean"
      }
    },
    "required": ["name", "type"],
    "additionalProperties": false
  },
  "type": "object",
  "properties": {
    "view": {
      "type": "string",
      "description": "Name of view"
    },
    "owner": {
      "type": "string",
      "description": "Team that is going to own the table"
    },
    "description": {
      "type": "string",
      "description": "Description of table"
    },
    "dependencies": {
      "description": "The other nodes that this node depends on",
      "type": "array",
      "items": {
        "oneOf": [{ "$ref": "#/definitions/table_dependency" }]
      }
    },
    "database": {
      "type": "string",
      "description": "Name of database table will be under"
    },
    "use_regional_values": {
      "type": "boolean",
      "description": "If true, the view's SQL may contain region specific template variables"
    },
    "schema": {
      "type": "array",
      "description": "Array of column objects containing name, type, and other columns",
      "items": {
        "$ref": "#/column"
      }
    },
    "regions": {
      "type": "array",
      "description": "Define the view in select AWS regions. Deploy to all regions by default if not specified.",
      "items": {
        "type": "string",
        "enum": ["us-west-2", "eu-west-1", "ca-central-1"],
        "minItems": 1
      }
    }
  },
  "required": ["owner", "description", "database", "schema"],
  "additionalProperties": false,

  "definitions": {
    "table_dependency": {
      "name": "table dependency",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "type": "object",
      "properties": {
        "dbname": {
          "type": "string"
        },
        "language": {
          "type": "string",
          "enum": ["python", "sql"]
        },
        "schema_path": {
          "type": "string"
        },
        "tablename": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": ["table"]
        },
        "external": {
          "type": "boolean"
        }
      },
      "required": ["dbname", "tablename", "type"],
      "additionalProperties": false
    }
  }
}

=== edie-yao-0207/datahubcursorllm-edie/dataplatform/tables/sqlview/dataprep/num_active_devices_weekly.json
{
  "view": "num_active_devices_weekly",
  "owner": "DataEngineering",
  "description": "This table contains a weekly history of active product devices and trips for external organizations",
  "database": "dataprep",
  "schema": [
    {
      "name": "week",
      "type": "date",
      "description": "The starting 'date' of the week in 'YYYY-mm-dd' format"
    },
    {
      "name": "product_id",
      "type": "long",
      "description": "The internal ID of the Samsara product"
    },
    {
      "name": "total_devices_heartbeats",
      "type": "long",
      "description": "The total number of product devices that had an active heartbeat in the calendar week"
    },
    {
      "name": "total_devices_trips",
      "type": "long",
      "description": "The total number of product devices with at least one trip on in the calendar week"
    }
  ],
  "dependencies": [
    {
      "dbname": "dataprep",
      "tablename": "active_devices",
      "type": "table"
    },
    {
      "external": true,
      "dbname": "clouddb",
      "tablename": "organizations",
      "type": "table"
    }
  ]
}

=== edie-yao-0207/datahubcursorllm-edie/dataplatform/tables/sqlview/datascience/idling_duration.json
{
  "view": "idling_duration",
  "owner": "DataScience",
  "description": "Get idling duration by org by day",
  "database": "datascience",
  "schema": [
    { "name": "org_id", "type": "long" },
    { "name": "date", "type": "date" },
    { "name": "on_duration_ms", "type": "long", "nullable": false },
    { "name": "idle_duration_ms", "type": "long", "nullable": false }
  ],
  "dependencies": [
    {
      "external": true,
      "dbname": "kinesisstats",
      "tablename": "osdenginestate",
      "type": "table"
    },
    {
      "external": true,
      "dbname": "productsdb",
      "tablename": "devices",
      "type": "table"
    },
    {
      "external": true,
      "dbname": "kinesisstats",
      "tablename": "osddigioinput1",
      "type": "table"
    },
    {
      "external": true,
      "dbname": "kinesisstats",
      "tablename": "osddigioinput2",
      "type": "table"
    },
    {
      "external": true,
      "dbname": "kinesisstats",
      "tablename": "osddigioinput3",
      "type": "table"
    },
    {
      "external": true,
      "dbname": "kinesisstats",
      "tablename": "osddigioinput4",
      "type": "table"
    },
    {
      "external": true,
      "dbname": "kinesisstats",
      "tablename": "osddigioinput5",
      "type": "table"
    },
    {
      "external": true,
      "dbname": "kinesisstats",
      "tablename": "osddigioinput6",
      "type": "table"
    },
    {
      "external": true,
      "dbname": "kinesisstats",
      "tablename": "osddigioinput7",
      "type": "table"
    },
    {
      "external": true,
      "dbname": "kinesisstats",
      "tablename": "osddigioinput8",
      "type": "table"
    },
    {
      "external": true,
      "dbname": "kinesisstats",
      "tablename": "osddigioinput9",
      "type": "table"
    },
    {
      "external": true,
      "dbname": "kinesisstats",
      "tablename": "osddigioinput10",
      "type": "table"
    },
    {
      "external": true,
      "dbname": "clouddb",
      "tablename": "organizations",
      "type": "table"
    },
    {
      "external": true,
      "dbname": "definitions",
      "tablename": "445_calendar",
      "type": "table"
    }
  ]
}

=== edie-yao-0207/datahubcursorllm-edie/dataplatform/tables/sqlview/datascience/imu_calibration_intervals.json
{
  "view": "imu_calibration_intervals",
  "owner": "DataScience",
  "description": "HEv2 IMU calibration state intervals",
  "database": "datascience",
  "schema": [
    { "name": "org_id", "type": "long", "nullable": true },
    { "name": "device_id", "type": "long", "nullable": true },
    { "name": "status", "type": "string", "nullable": false },
    { "name": "source", "type": "string", "nullable": true },
    { "name": "start_ms", "type": "long", "nullable": true },
    { "name": "end_ms", "type": "long", "nullable": true },
    { "name": "next_status", "type": "string", "nullable": true },
    { "name": "next_source", "type": "string", "nullable": true }
  ],
  "dependencies": [
    {
      "external": true,
      "dbname": "kinesisstats",
      "tablename": "osdimuorientation",
      "type": "table"
    },
    {
      "external": true,
      "dbname": "kinesisstats",
      "tablename": "osdimucalibrationreset",
      "type": "table"
    }
  ]
}

=== edie-yao-0207/datahubcursorllm-edie/dataplatform/tables/sqlview/platops/samnumber_accuracy_serial_match.json
{
  "view": "samnumber_accuracy_serial_match",
  "owner": "PlatformOperations",
  "description": "This view connects serials to related samnumber in cloud and ns. This is useful to find differences between the systems",
  "database": "platops",
  "schema": [
    { "name": "org_id", "type": "long", "description": "Id for the organization" },
    {
      "name": "sam_number",
      "type": "string",
      "description": "Samnumber is a unique id that ties customer accounts together in Netsuite, Salesforce, and Samsara cloud dashboard."
    },
    {
      "name": "total_serials",
      "type": "long",
      "nullable": false,
      "description": "Total count of serials for this organization"
    },
    {
      "name": "mismatched_serials",
      "type": "long",
      "nullable": false,
      "description": "Total count of serials with differing serials for this organization."
    },
    { "name": "percent_serial_mismatch", "type": "double", "description": "mismatched_serials/total_serials" }
  ],
  "dependencies": [
    {
      "dbname": "platops",
      "tablename": "serial_to_samnumber",
      "type": "table"
    },
    {
      "external": true,
      "dbname": "netsuite_data",
      "tablename": "serial_to_samnumber",
      "type": "table"
    },
    {
      "dbname": "clouddb",
      "tablename": "org_sfdc_accounts",
      "type": "table"
    },
    {
      "external": true,
      "dbname": "clouddb",
      "tablename": "users_organizations",
      "type": "table"
    }
  ]
}

=== edie-yao-0207/datahubcursorllm-edie/dataplatform/tables/sqlview/billing/dataplatform_costs_latest_full_date.json
{
  "view": "dataplatform_costs_latest_full_date",
  "owner": "DataPlatform",
  "description": "This view contains a single row with a single column, date, containing the latest day that has complete data in dataplatform_costs. This is necessary because databricks and aws data come at different cadences so there are times in which we may have partial data, so data after this date isn't complete.",
  "database": "billing",
  "regions": ["us-west-2"],
  "schema": [
    {
      "name": "date",
      "type": "date",
      "description": "The latest day that is fully valid in dataplatform_costs."
    }
  ],
  "dependencies": [
    {
      "dbname": "billing",
      "tablename": "dataplatform_costs",
      "type": "table",
      "external": true
    }
  ]
}

=== edie-yao-0207/datahubcursorllm-edie/dataplatform/tables/sqlview/product_analytics/agg_product_scorecard_platform_mpr_global.json
{
  "view": "agg_product_scorecard_platform_mpr_global",
  "owner": "DataEngineering",
  "description": "This view contains both weekly and monthly Platform MPR metrics",
  "database": "product_analytics",
  "regions": ["us-west-2"],
  "schema": [
    { "name": "period", "type": "string", "nullable": false, "description": "Period type (week or month)" },
    { "name": "date", "type": "string", "description": "Date partition" },
    { "name": "period_start", "type": "string", "description": "Start of period" },
    { "name": "period_end", "type": "string", "description": "End of period" },
    { "name": "cloud_region", "type": "string", "description": "Cloud region of SAM grouping" },
    { "name": "region", "type": "string", "description": "Region of SAM grouping (USA - Midwest, USA - West, etc.)" },
    { "name": "account_size_segment", "type": "string", "description": "Account size segment of grouping" },
    { "name": "account_arr_segment", "type": "string", "description": "Account ARR segment of grouping" },
    { "name": "account_industry", "type": "string", "description": "Account industry of grouping" },
    { "name": "industry_vertical", "type": "string", "description": "Industry vertical of grouping" },
    {
      "name": "is_paid_safety_customer",
      "type": "boolean",
      "description": "Whether the SAM has Safety licenses or not"
    },
    {
      "name": "is_paid_telematics_customer",
      "type": "boolean",
      "description": "Whether the SAM has Telematics licenses or not"
    },
    { "name": "is_paid_stce_customer", "type": "boolean", "description": "Whether the SAM has STCE licenses or not" },
    {
      "name": "full_admin_orgs",
      "type": "long",
      "description": "Total number of orgs having all users as admins"
    },
    {
      "name": "custom_role_orgs",
      "type": "long",
      "description": "Total number of orgs having at least one user with a custom role"
    },
    {
      "name": "total_orgs",
      "type": "long",
      "description": "Total number of orgs with 2+ users at the end of the period"
    },
    {
      "name": "device_attributes",
      "type": "long",
      "description": "Total number of devices having at least one attribute"
    },
    {
      "name": "device_attributes_orgs",
      "type": "long",
      "description": "Total number of orgs having a device with at least one attribute"
    },
    {
      "name": "device_tags",
      "type": "long",
      "description": "Total number of devices having at least one tag"
    },
    {
      "name": "device_tags_orgs",
      "type": "long",
      "description": "Total number of orgs having a device with at least one tag"
    },
    {
      "name": "device_tags_attributes",
      "type": "long",
      "description": "Total number of devices having at least one tag and at least one attribute"
    },
    {
      "name": "total_devices",
      "type": "long",
      "description": "Number of devices within the grouping"
    },
    {
      "name": "total_device_orgs",
      "type": "long",
      "description": "Number of orgs with a device within the grouping"
    },
    {
      "name": "driver_tags",
      "type": "long",
      "description": "Total number of drivers having at least one tag"
    },
    {
      "name": "driver_tags_orgs",
      "type": "long",
      "description": "Total number of orgs having a driver with at least one tag"
    },
    {
      "name": "driver_attributes",
      "type": "long",
      "description": "Total number of drivers having at least one attribute"
    },
    {
      "name": "driver_attributes_orgs",
      "type": "long",
      "description": "Total number of orgs having a driver with at least one attribute"
    },
    {
      "name": "driver_tags_attributes",
      "type": "long",
      "description": "Total number of drivers having at least one tag and at least one attribute"
    },
    {
      "name": "total_drivers",
      "type": "long",
      "description": "Number of drivers within the grouping"
    },
    {
      "name": "total_driver_orgs",
      "type": "long",
      "description": "Number of orgs with a driver within the grouping"
    },
    {
      "name": "csv_upload_failures",
      "type": "long",
      "description": "Number of CSV uploads with at least one error row"
    },
    { "name": "csv_uploads", "type": "long", "description": "Number of CSV uploads" },
    {
      "name": "average_row_error_rate",
      "type": "decimal(38,20)",
      "description": "Average error rate (rows errored/rows submitted) for CSV uploads"
    },
    {
      "name": "active_cloud_dashboard_users",
      "type": "long",
      "description": "Number of users who have logged into the Cloud Dashboard within the period"
    },
    {
      "name": "active_cloud_dashboard_orgs",
      "type": "long",
      "description": "Number of orgs who have logged into the Cloud Dashboard within the period"
    },
    {
      "name": "total_possible_cloud_dashboard_users",
      "type": "long",
      "description": "Number of users who were a part of the org during the period"
    }
  ],
  "dependencies": [
    {
      "external": true,
      "dbname": "product_analytics",
      "tablename": "agg_product_scorecard_platform_mpr_global_weekly",
      "type": "table"
    },
    {
      "external": true,
      "dbname": "product_analytics",
      "tablename": "agg_product_scorecard_platform_mpr_global_monthly",
      "type": "table"
    }
  ]
}

=== edie-yao-0207/datahubcursorllm-edie/dataplatform/tables/sqlview/product_analytics/agg_product_scorecard_safety_mpr_filtered_global.json
{
  "view": "agg_product_scorecard_safety_mpr_filtered_global",
  "owner": "DataEngineering",
  "description": "This view contains the latest safety MPR metrics data",
  "database": "product_analytics",
  "regions": ["us-west-2"],
  "schema": [
    { "name": "date", "type": "string", "description": "Date partition" },
    { "name": "period_start", "type": "string", "description": "Start of period" },
    { "name": "period_end", "type": "string", "description": "End of period" },
    { "name": "sam_number", "type": "string", "description": "SAM number for set of orgs" },
    { "name": "account_size_segment", "type": "string", "description": "Account size segment of grouping" },
    { "name": "account_arr_segment", "type": "string", "description": "Account ARR segment of grouping" },
    { "name": "account_billing_country", "type": "string", "description": "Billing country of the account" },
    { "name": "account_industry", "type": "string", "description": "Account industry of grouping" },
    { "name": "industry_vertical", "type": "string", "description": "Industry vertical of grouping" },
    {
      "name": "is_paid_safety_customer",
      "type": "boolean",
      "description": "Whether the SAM has Safety licenses or not"
    },
    {
      "name": "is_paid_telematics_customer",
      "type": "boolean",
      "description": "Whether the SAM has Telematics licenses or not"
    },
    { "name": "is_paid_stce_customer", "type": "boolean", "description": "Whether the SAM has STCE licenses or not" },
    { "name": "account_csm_email", "type": "string", "description": "CSM email of the account" },
    { "name": "account_name", "type": "string", "description": "Name of the account" },
    { "name": "account_id", "type": "string", "description": "ID of the account" },
    { "name": "account_created_date", "type": "string", "description": "Creation date of the account" },
    {
      "name": "dual_facing_cam",
      "type": "boolean",
      "description": "Whether account has at least one dual-facing cam or not"
    },
    {
      "name": "account_renewal_12mo",
      "type": "boolean",
      "description": "Whether account has 50% of their licenses up for renewal within the next 12 months or not"
    },
    {
      "name": "total_drivers",
      "type": "long",
      "description": "Total number of drivers in the account"
    },
    {
      "name": "total_drivers_using_app_month",
      "type": "long",
      "description": "Total number of drivers who have used the Mobile App in the last month"
    },
    {
      "name": "total_drivers_using_app",
      "type": "long",
      "description": "Total number of drivers who have used the Mobile App"
    },
    {
      "name": "assigned_trainings",
      "type": "long",
      "description": "Total number of assigned trainings in the account that were initiated in the month"
    },
    {
      "name": "total_drivers_assigned_training",
      "type": "long",
      "description": "Total number of drivers who were assigned to training events in the account that were initiated in the month"
    },
    {
      "name": "total_drivers_completing_training_on_time",
      "type": "long",
      "description": "Total number of drivers who completed training events in the account that were initiated in the month"
    },
    {
      "name": "drivers_completing_manager_led_coaching",
      "type": "long",
      "description": "Total number of drivers who completed coaching sessions connected to a manager-led coaching event in the account that were initiated in the month"
    },
    {
      "name": "drivers_completing_self_coaching",
      "type": "long",
      "description": "Total number of drivers who completed coaching sessions connected to a self coaching event in the account that were initiated in the month"
    },
    {
      "name": "drivers_completing_coaching",
      "type": "long",
      "description": "Total number of drivers who completed coaching sessions in the account that were initiated in the month"
    },
    {
      "name": "miles",
      "type": "double",
      "description": "Total number of miles covered by trips for devices enabled for at least one event type in the account for the month"
    }
  ],
  "dependencies": [
    {
      "external": true,
      "dbname": "product_analytics",
      "tablename": "agg_product_scorecard_safety_mpr_global_revised_monthly",
      "type": "table"
    }
  ]
}

=== edie-yao-0207/datahubcursorllm-edie/dataplatform/tables/sqlview/datascience/gvwr_vehicle_types.json
{
  "view": "gvwr_vehicle_types",
  "owner": "DataScience",
  "description": "Gross Vehicle Weight Rating for a given make and model between clouddb and vindb",
  "database": "datascience",
  "schema": [
    { "name": "make", "type": "string" },
    { "name": "model", "type": "string" },
    { "name": "gvwr_vehicle_type", "nullable": false, "type": "string" }
  ],
  "dependencies": [
    {
      "external": true,
      "dbname": "clouddb",
      "tablename": "vehicle_make_model_weights",
      "type": "table"
    },
    {
      "external": true,
      "dbname": "vindb_shards",
      "tablename": "device_vin_metadata",
      "type": "table"
    }
  ]
}
